name: "Test rosbag2_bag_v2"
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: ros-tooling/setup-ros2@0.0.8
      with:
        required-ros-distributions: melodic
    - uses: ros-tooling/action-ros2-ci@0.0.11
      with:
        package-name: ros1_rosbag_storage_vendor rosbag2_bag_v2_plugins
        source-ros-binary-installation: melodic
